name: Node CI

on:
  push:
    branches:
      - next
      - feat/**
  pull_request:
    branches:
      - next

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JS
        uses: sxzz/workflows/setup-js@866f46ed892502b45a58ba4de02987123ccf8e17
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm start

      - name: build
        run: pnpm build

  demos:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: demo
            cmd: pnpm build:demo
          - name: demo-v4-h5
            cmd: pnpm --filter demo-v4 run build:h5
          - name: demo-v5-weapp
            cmd: pnpm --filter demo-v5 run build:weapp
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JS
        uses: sxzz/workflows/setup-js@866f46ed892502b45a58ba4de02987123ccf8e17
        with:
          node-version: 18.x

      - name: Run demo build
        run: ${{ matrix.cmd }}
