name: Test CI

on:
  push:
    branches:
      - next
      - feat/**
  pull_request:
    branches:
      - next

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Taro UI
        run: pnpm --filter taro-ui build
      - name: Test Taro UI
        run: pnpm --filter taro-ui test
