name: Test CI

on:
  push:
    branches:
      - next
      - feat/**
  pull_request:
    branches:
      - next

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 JS 环境
        uses: sxzz/workflows/setup-js@main
        with:
          node-version: '24.x'
      - name: 构建 Taro UI
        run: pnpm --filter taro-ui build
      - name: 测试 Taro UI
        run: pnpm --filter taro-ui test
